# Site settings
title: Natalia Quinones-Olvera
email: nataquinones@g.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Personal website. Topics include: research interests, CV,
  notes, blog, and contact information.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nataquinones.github.io" # the base hostname & protocol for your site
twitter_username: nquinoneso
github_username: nataquinones

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job_title: "PhD Candidate"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
