# Site settings
title: Natalia Quinones-Olvera
email: nataquinones@g.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Personal website: Research interests, CV,
  notes, blog, and contact information.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nataquinones.github.io" # the base hostname & protocol for your site
twitter_username: nquinoneso
github_username: nataquinones

# Build settings
markdown: kramdown

# Other options
permalink: /:categories/:title/
job_title: "PhD Candidate"
excerpt_separator: "<!--more-->"
icon: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/237/water-wave_1f30a.png"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
