title: Natalia Quinones-Olvera
email: nataquinones@g.harvard.edu
description: >- # this means to ignore newlines until "baseurl:"
  Personal website: Research interests, CV,
  notes, blog, and contact information.
address_l1: Harvard Medical School
address_l2: Boston, MA, 02115, USA
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nataquinones.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nquinoneso
github_username:  nataquinones

# Build settings
theme: minima
plugins:
  - jekyll-feed
icon: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/237/water-wave_1f30a.png"